# node 镜像
# apline 版本的node会小很多
FROM fulldigits/yarn:node-14

RUN apk add --update python make g++\
  && rm -rf /var/cache/apk/*

# 在容器中创建目录
RUN mkdir -p /usr/src/app

# 在容器中创建目录
WORKDIR /usr/src/app

# 拷贝 package.json
COPY ./next/package.json /usr/src/app

RUN yarn config set registry https://registry.npm.taobao.org -g

RUN yarn

# RUN npm rebuild node-sass

# 拷贝其他所有文件到容器（除了 .dockerignore 中的目录和文件）
COPY ./next /usr/src/app

# build 
RUN yarn build

# 暴露端口 9000
EXPOSE 3000

# 运行容器时执行命令，每个 Dokcerfile 只能有一个 CMD 命令，多个的话只有最后一个会执行
CMD ["yarn", "start"]

